resources:
  repositories:
    - repository: Pipelines
      type: git
      name: EAG/Pipelines
      ref: TemplateV2
name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

variables:
- name: buildConfiguration
  value: 'Release'
- name: BuildPlatform
  value: 'any cpu'
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 30
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 30
pool:
  name: 'Default'
  demands:
  - VM
trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - src/azure-pipelines.yml
    - src/Services/Administration/IAC/IdentityAndAccessControl.Api/azure-pipelines.yml
  batch: True
extends:
  template: jobtemplates/coreapidbwithoutsonar.yml@Pipelines
  parameters:
    runGitLeaks: 'false'
    nugetAuthenticateServiceConnections: 'Softura_LIB'
    dotnetrestoresolutionpath: 'src/Services/Administration/IAC/IAC.Api/IAC.Api.csproj'
    dotnetPublishProjectPath: 'src/Services/Administration/IAC/IAC.Api/IAC.Api.csproj'
    dotnetrestorevstsfeed: 'eead0206-6959-4e49-b193-074e4872ef5d/e15077aa-1401-474b-b7fe-9ed881bc7c8c'
    dbSolutionPath: 'src/Database/FCC.NextGen.Database/FCC.NextGen.Database.sln'
    copyFilesContents: '**'
    copyFilesSourceFolder: 'src/Database/FCC.NextGen.Database/FCC.NextGen.Database'