
export { default as komatsu } from './404.svg';
export { default as close } from './Close_SuccessPopup.svg';
export { default as viewIcon } from './Eye.svg';
export { default as downloadIcon } from './Download.svg';
export { default as deleteIcon } from './Delete.svg';
export { default as uploadIcon } from './Upload.svg';
export { default as logo } from './NexGen.svg';
export { default as editpen_White } from './EditRow.svg';
export { default as save_White } from './SaveRow.svg';
export { default as close_White } from './DeleteRow.svg';
export { default as CloseIcon } from './close.png';
export { default as dashboardIcon } from './Home.svg';
export { default as exportIcon } from './Chevron.svg';
export { default as CPQIcon } from './CPQ.svg';
export { default as scheduleIcon } from './Schedule.svg';
export { default as eticketIcon } from './ETicket.svg';
export { default as invoiceIcon } from './Invoice.svg';
export { default as maintenanceIcon } from './Maintenance.svg';
export { default as inventoryIcon } from './Inventory.svg';
export { default as safetyIcon } from './Safety.svg';
export { default as biIcon } from './BI.svg';
export { default as settingIcon } from './Settings.svg';
export { default as whatsNewIcon } from './whatsNew.svg';
export { default as logoutIcon } from './Logout.svg';
export { default as rightArrow } from './RightArrow.svg';
export { default as InfoIcon } from './Info.svg';
export { default as ClockIcon } from './Clock.svg'
export { default as CalenderIcon } from './Calendar.svg'
export { default as plusIcon } from './PlusDI.png'
export { default as email } from './email.jpg';
export { default as location } from './location.jpg';
export { default as Clock } from './Clock.svg'
export { default as Calendar } from './Calendar.svg'

